services:
  - type: web
    name: scalping-render-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: "10000"
      - key: TELEGRAM_PORT
        value: "8443"
      - key: RENDER_EXTERNAL_HOSTNAME
        value: scalping-render-bot.onrender.com
